package edu.formas.FM3S6.modelo.entidad;
// Generated 11-09-2021 06:50:41 PM by Hibernate Tools 4.3.1


import edu.formas.FM3S6.modelo.dao.daoCuenta;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name="cuenta"
    ,catalog="modulo3"
)
public class Cuenta  implements java.io.Serializable {


     private Integer numeroCuenta;
     private Cliente cliente;
     private Float saldo;
     private List<Abonos> lstAbonos;

    public Cuenta() {
        this.lstAbonos = new ArrayList<>();
        this.saldo = 0f;
    }

	
    public Cuenta(Cliente cliente) {
        this.cliente = cliente;
        this.saldo = 0f;
    }
    public Cuenta(Cliente cliente, Float saldo, List<Abonos> lst) {
       this.cliente = cliente;
       this.saldo = saldo;
       this.lstAbonos = lst;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="numeroCuenta", unique=true, nullable=false)
    public Integer getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(Integer numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }    
    
    @Column(name="saldo", precision=10)
    public Float getSaldo() {
        daoCuenta daoC = new daoCuenta();
        this.saldo = daoC.calcularSaldo(this);
        return this.saldo;
    }
    
    public void setSaldo(Float saldo) {
        this.saldo = saldo;
    }
     @Transient
    @OneToMany(fetch=FetchType.LAZY, mappedBy="cuenta")
    public List<Abonos> getAbonos() {
        return this.lstAbonos;
    }
   
    public void setAbonos(List<Abonos> lst) {
        this.lstAbonos = lst;
    }




}


