package edu.formas.FM3S6.modelo.entidad;
// Generated 11-09-2021 06:50:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="modulo3"
)
public class Usuario  implements java.io.Serializable {


     private String login;
     private String nombre;
     private String apellido;
     private String clave;

    public Usuario() {
    }

	
    public Usuario(String login) {
        this.login = login;
    }
    public Usuario(String login, String nombre, String apellido, String clave) {
       this.login = login;
       this.nombre = nombre;
       this.apellido = apellido;
       this.clave = clave;
    }
   
     @Id 

    
    @Column(name="login", unique=true, nullable=false, length=20)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=100)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="clave", length=100)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


