package edu.formas.FM2S8.modelo.entidad;
// Generated 11-16-2021 06:36:58 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="evaluacionm3"
)
public class Usuario  implements java.io.Serializable {


     private String login;
     private String clave;

    public Usuario() {
    }

	
    public Usuario(String login) {
        this.login = login;
    }
    public Usuario(String login, String clave) {
       this.login = login;
       this.clave = clave;
    }
   
     @Id 

    
    @Column(name="login", unique=true, nullable=false, length=20)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="clave", length=100)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


