package pojos;
// Generated 11-04-2021 07:06:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Abonos generated by hbm2java
 */
@Entity
@Table(name="abonos"
    ,catalog="evaluacionm2"
)
public class Abonos  implements java.io.Serializable {


     private Integer idAbono;
     private Cuenta cuenta;
     private Date fechaAbono;
     private Float montoAbono;

    public Abonos() {
    }

    public Abonos(Cuenta cuenta, Date fechaAbono, Float montoAbono) {
       this.cuenta = cuenta;
       this.fechaAbono = fechaAbono;
       this.montoAbono = montoAbono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAbono", unique=true, nullable=false)
    public Integer getIdAbono() {
        return this.idAbono;
    }
    
    public void setIdAbono(Integer idAbono) {
        this.idAbono = idAbono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="numeroCuenta")
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaAbono", length=10)
    public Date getFechaAbono() {
        return this.fechaAbono;
    }
    
    public void setFechaAbono(Date fechaAbono) {
        this.fechaAbono = fechaAbono;
    }

    
    @Column(name="montoAbono", precision=10)
    public Float getMontoAbono() {
        return this.montoAbono;
    }
    
    public void setMontoAbono(Float montoAbono) {
        this.montoAbono = montoAbono;
    }




}


