package edu.formas.modelo.entidad;
// Generated 10-28-2021 08:42:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name="cuenta"
    ,catalog="evaluacionm2"
)
public class Cuenta  implements java.io.Serializable {


     private Integer numeroCuenta;
     private Cliente cliente;
     private Float saldo;
     private Set abonoses = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(Cliente cliente) {
        this.cliente = cliente;
    }
    public Cuenta(Cliente cliente, Float saldo, Set abonoses) {
       this.cliente = cliente;
       this.saldo = saldo;
       this.abonoses = abonoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="numeroCuenta", unique=true, nullable=false)
    public Integer getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(Integer numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="saldo", precision=10)
    public Float getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Float saldo) {
        this.saldo = saldo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuenta")
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }




}


