package modelo.entidad;
// Generated 12-02-2021 06:25:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", catalog = "cliente")
public class Clientes implements java.io.Serializable {

    private Integer idclientes;
    private String nombre;
    private String apellido;

    public Clientes() {
    }

    public Clientes(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idclientes", unique = true, nullable = false)
    public Integer getIdclientes() {
        return this.idclientes;
    }

    public void setIdclientes(Integer idclientes) {
        this.idclientes = idclientes;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "apellido", length = 45)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

}
